import type { Metadata } from 'next';
import './globals.scss';
import Providers from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/tetris.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Tetris Multiplayer</title>
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
